### ISSUE TITLE
django-test-suite: admin_changelist test_multiuser_edit failure

### ISSUE THREAD

**Issue by odeke-em** [googleapis/python-spanner-django#135]
- [ ] test_multiuser_edit

fails currently with
```
======================================================================
FAIL: test_multiuser_edit (admin_changelist.tests.ChangeListTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/emmanuelodeke/Desktop/spanner-orm/django_tests/django/tests/admin_changelist/tests.py", line 760, in test_multiuser_edit
    self.assertContains(response, '1 swallow was changed successfully.')
  File "/Users/emmanuelodeke/Desktop/spanner-orm/django_tests/django/django/test/testcases.py", line 454, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find '1 swallow was changed successfully.' in response
```

**Comment by timgraham** [comment]
I can't reproduce a failure so I guess this was fixed since it was reported.
