### ISSUE TITLE
django: Cursor.description returns None on raw queries

### ISSUE THREAD

**Issue by timgraham** [googleapis/python-spanner-django#155]
I'm not familiar enough with [the code](https://github.com/orijtech/spanner-orm/blob/f0d203df800a52243ef2410b141fa2fd0e313525/spanner/dbapi/cursor.py#L38-L47) to say if this is a bug or if it's a limitation of Spanner. Example failure:
```
======================================================================
ERROR: test_FK_raw_query (raw_query.tests.RawQueryTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/raw_query/tests.py", line 124, in test_FK_raw_query
    self.assertSuccessfulRawQuery(Book, query, books)
  File "/home/tim/code/django/tests/raw_query/tests.py", line 53, in assertSuccessfulRawQuery
    results = list(model.objects.raw(query, params=params, translations=translations))
  File "/home/tim/code/django/django/db/models/query.py", line 1395, in __iter__
    self._fetch_all()
  File "/home/tim/code/django/django/db/models/query.py", line 1382, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/tim/code/django/django/db/models/query.py", line 1408, in iterator
    model_init_names, model_init_pos, annotation_fields = self.resolve_model_init_order()
  File "/home/tim/code/django/django/db/models/query.py", line 1351, in resolve_model_init_order
    model_init_fields = [f for f in self.model._meta.fields if converter(f.column) in self.columns]
  File "/home/tim/code/django/django/db/models/query.py", line 1351, in <listcomp>
    model_init_fields = [f for f in self.model._meta.fields if converter(f.column) in self.columns]
  File "/home/tim/code/django/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/tim/code/django/django/db/models/query.py", line 1457, in columns
    columns = self.query.get_columns()
  File "/home/tim/code/django/django/db/models/sql/query.py", line 97, in get_columns
    for column_meta in self.cursor.description]
TypeError: 'NoneType' object is not iterable
```

**Comment by jerryleooo** [comment]
still meet this in 4.1.6 with Model's  `objects.raw` API
