### ISSUE TITLE
django: Spanner's TIMESTAMP_TRUNC seems not to respect time_zone

### ISSUE THREAD

**Issue by timgraham** [googleapis/python-spanner-django#193]
Example failure:
```
======================================================================
FAIL: test_21432 (datetimes.tests.DateTimesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/django/test/utils.py", line 373, in inner
    return func(*args, **kwargs)
  File "/home/tim/code/django/tests/datetimes/tests.py", line 92, in test_21432
    self.assertEqual(qs[0], now)
AssertionError: datet[22 chars] 14, 22, 37, 15, tzinfo=<DstTzInfo 'America/Ch[27 chars]STD>) != datet[22 chars] 14, 16, 37, 15, tzinfo=<DstTzInfo 'America/Ch[27 chars]STD>)
```

**Comment by timgraham** [comment]
Summarizing this issue again:
```sql
CREATE TABLE issue260 (
    id INT64 NOT NULL,
    pub_date TIMESTAMP,
) PRIMARY KEY (id)

INSERT INTO issue260 (id, pub_date) VALUES (1, '2020-04-17T00:07:07.000000Z')

# Different time zones give the same result?

> SELECT DISTINCT TIMESTAMP_TRUNC(issue260.pub_date, second, "America/Chicago") AS datetimefield FROM issue260
2020-04-17T00:07:07Z 

> SELECT DISTINCT TIMESTAMP_TRUNC(issue260.pub_date, second, "America/New_York") AS datetimefield FROM issue260
2020-04-17T00:07:07Z 

# Same (unexpected) result with a different date_part value.

> SELECT DISTINCT TIMESTAMP_TRUNC(issue260.pub_date, minute, "America/Chicago") AS datetimefield FROM issue260
2020-04-17T00:07:00Z 

> SELECT DISTINCT TIMESTAMP_TRUNC(issue260.pub_date, minute, "America/New_York") AS datetimefield FROM issue260
2020-04-17T00:07:00Z 

# Expected results (e.g. from PostgreSQL)... time zone affects the hour that's returned.

> SELECT DISTINCT DATE_TRUNC('second', issue260.pub_date) AT TIME ZONE 'America/Chicago' AS datetimefield FROM issue260
"2020-04-17 01:07:07-04"

> SELECT DISTINCT DATE_TRUNC('second', issue260.pub_date) AT TIME ZONE 'America/New_York' AS datetimefield FROM issue260
"2020-04-17 00:07:07-04"
```
@skuruppu can you explain this? I'm not understanding Spanner's handling of time zones. #260 and #191 are related issues.

**Comment by skuruppu** [comment]
Hopefully my explanation in https://github.com/googleapis/python-spanner-django/issues/191#issuecomment-617699245 will help to clarify what's happening. But let me know if it doesn't make sense.
