### ISSUE TITLE
django: using NULL with + crashes

### ISSUE THREAD

**Issue by timgraham** [googleapis/python-spanner-django#201]
Example failure:
```
======================================================================
ERROR: test_combined_annotation_commutative (annotations.tests.NonAggregateAnnotationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/.virtualenvs/django37/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 79, in next
    return six.next(self._wrapped)
  File "/home/tim/.virtualenvs/django37/lib/python3.7/site-packages/grpc/_channel.py", line 392, in __next__
    return self._next()
  File "/home/tim/.virtualenvs/django37/lib/python3.7/site-packages/grpc/_channel.py", line 561, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Operands of + cannot be literal NULL [at 1:261]\n...pubdate, (annotations_book.rating + NULL) AS adjusted_rating FROM annotati...\n                                       ^"
	debug_error_string = "{"created":"@1587687568.948721860","description":"Error received from peer ipv4:172.217.10.74:443","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Operands of + cannot be literal NULL [at 1:261]\n...pubdate, (annotations_book.rating + NULL) AS adjusted_rating FROM annotati...\n                                       ^","grpc_status":3}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/code/spanner-django/spanner_dbapi/cursor.py", line 83, in execute
    self.__handle_DQL(sql, args or None)
  File "/home/tim/code/spanner-django/spanner_dbapi/cursor.py", line 181, in __handle_DQL
    self._itr = PeekIterator(self._res)
  File "/home/tim/code/spanner-django/spanner_dbapi/utils.py", line 25, in __init__
    head = next(itr_src)
  File "/home/tim/.virtualenvs/django37/lib/python3.7/site-packages/google/cloud/spanner_v1/streamed.py", line 143, in __iter__
    self._consume_next()
  File "/home/tim/.virtualenvs/django37/lib/python3.7/site-packages/google/cloud/spanner_v1/streamed.py", line 116, in _consume_next
    response = six.next(self._response_iterator)
  File "/home/tim/.virtualenvs/django37/lib/python3.7/site-packages/google/cloud/spanner_v1/snapshot.py", line 45, in _restart_on_unavailable
    for item in iterator:
  File "/home/tim/.virtualenvs/django37/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 81, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 Operands of + cannot be literal NULL [at 1:261]\n...pubdate, (annotations_book.rating + NULL) AS adjusted_rating FROM annotati...\n                                       ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/code/django/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tim/code/spanner-django/spanner_dbapi/cursor.py", line 91, in execute
    raise ProgrammingError(e.details if hasattr(e, 'details') else e)
spanner_dbapi.exceptions.ProgrammingError: 400 Operands of + cannot be literal NULL [at 1:261]\n...pubdate, (annotations_book.rating + NULL) AS adjusted_rating FROM annotati...\n                                       ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/code/django/tests/annotations/tests.py", line 270, in test_combined_annotation_commutative
    book1 = Book.objects.annotate(adjusted_rating=F('rating') + None).get(pk=self.b1.pk)
  File "/home/tim/code/django/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/home/tim/code/django/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/home/tim/code/django/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/tim/code/django/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/tim/code/django/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/tim/code/django/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tim/code/django/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tim/code/django/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tim/code/spanner-django/spanner_dbapi/cursor.py", line 91, in execute
    raise ProgrammingError(e.details if hasattr(e, 'details') else e)
django.db.utils.ProgrammingError: 400 Operands of + cannot be literal NULL [at 1:261]\n...pubdate, (annotations_book.rating + NULL) AS adjusted_rating FROM annotati...\n            
```

**Comment by timgraham** [comment]
I don't see a way to fix this but I don't think it's critical. I've added a commit to https://github.com/googleapis/python-spanner-django/pull/432 to document the limitation.

**Comment by asthamohta** [comment]
This is a documented limitation as you can see here: https://github.com/googleapis/python-spanner-django/pull/432
This is currently on our roadmap so closing this issue
