### ISSUE TITLE
django: implement SchemaEditor.quote_value()

### ISSUE THREAD

**Issue by timgraham** [googleapis/python-spanner-django#227]
For example:
```
======================================================================
ERROR: test_extra_args (schema.test_logging.SchemaLoggerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/schema/test_logging.py", line 12, in test_extra_args
    editor.execute(sql, params)
  File "/home/tim/code/django/django/db/backends/base/schema.py", line 132, in execute
    self.collected_sql.append((sql % tuple(map(self.quote_value, params))) + ending)
  File "/home/tim/code/django/django/db/backends/base/schema.py", line 243, in quote_value
    raise NotImplementedError()
NotImplementedError
```

**Comment by timgraham** [comment]
It looks like the usage of `quote_value()` is limited to conditional indexes and constraints which Spanner doesn't support, so I don't think this is high priority.
```
django/db/models/indexes.py:        return sql % tuple(schema_editor.quote_value(p) for p in params)
django/db/models/constraints.py:        return sql % tuple(schema_editor.quote_value(p) for p in params)
```
