### ISSUE TITLE
dbapi: pyformat parameters not supported on INSERT

### ISSUE THREAD

**Issue by timgraham** [googleapis/python-spanner-django#343]
```
======================================================================
ERROR: test_cursor_execute_with_pyformat (backends.tests.BackendTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tim/code/spanner-orm/spanner/dbapi/autocommit_on_cursor.py", line 93, in execute
    self.__handle_insert(sql, args or None)
  File "/home/tim/code/spanner-orm/spanner/dbapi/autocommit_on_cursor.py", line 121, in __handle_insert
    parts = parse_insert(sql, params)
  File "/home/tim/code/spanner-orm/spanner/dbapi/parse_utils.py", line 158, in parse_insert
    _, values = parse_values(values_str)
  File "/home/tim/code/spanner-orm/spanner/dbapi/parser.py", line 143, in parse_values
    return expect(stmt, VALUES)
  File "/home/tim/code/spanner-orm/spanner/dbapi/parser.py", line 160, in expect
    word, arg = expect(word, ARGS)
  File "/home/tim/code/spanner-orm/spanner/dbapi/parser.py", line 218, in expect
    word, parsed = expect(word, FUNC)
  File "/home/tim/code/spanner-orm/spanner/dbapi/parser.py", line 181, in expect
    raise ProgrammingError('FUNC: `%s` does not begin with `a-zA-z` nor a `_`' % word)
spanner.dbapi.exceptions.ProgrammingError: FUNC: `%(root)s, %(square)s)` does not begin with `a-zA-z` nor a `_`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/code/django/django/test/testcases.py", line 1229, in skip_wrapper
    return test_func(*args, **kwargs)
  File "/home/tim/code/django/tests/backends/tests.py", line 266, in test_cursor_execute_with_pyformat
    self.create_squares(args, 'pyformat', multiple=False)
  File "/home/tim/code/django/tests/backends/tests.py", line 233, in create_squares
    cursor.execute(query, args)
  File "/home/tim/code/django/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/tim/code/django/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tim/code/django/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tim/code/django/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tim/code/spanner-orm/spanner/dbapi/autocommit_on_cursor.py", line 93, in execute
    self.__handle_insert(sql, args or None)
  File "/home/tim/code/spanner-orm/spanner/dbapi/autocommit_on_cursor.py", line 121, in __handle_insert
    parts = parse_insert(sql, params)
  File "/home/tim/code/spanner-orm/spanner/dbapi/parse_utils.py", line 158, in parse_insert
    _, values = parse_values(values_str)
  File "/home/tim/code/spanner-orm/spanner/dbapi/parser.py", line 143, in parse_values
    return expect(stmt, VALUES)
  File "/home/tim/code/spanner-orm/spanner/dbapi/parser.py", line 160, in expect
    word, arg = expect(word, ARGS)
  File "/home/tim/code/spanner-orm/spanner/dbapi/parser.py", line 218, in expect
    word, parsed = expect(word, FUNC)
  File "/home/tim/code/spanner-orm/spanner/dbapi/parser.py", line 181, in expect
    raise ProgrammingError('FUNC: `%s` does not begin with `a-zA-z` nor a `_`' % word)
django.db.utils.ProgrammingError: FUNC: `%(root)s, %(square)s)` does not begin with `a-zA-z` nor a `_`
```

**Comment by vi3k6i5** [comment]
This has to be resolved in python spanner and has been moved there: https://github.com/googleapis/python-spanner/issues/542
