### ISSUE TITLE
django: primary key values are lost after Model.save() with Django 3.0.x

### ISSUE THREAD

**Issue by odeke-em** [googleapis/python-spanner-django#398]
Just attempting to test out https://healthchecks.io's Django app and when trying to signup a user
![Screen Shot 2020-03-30 at 5 39 45 PM](https://user-images.githubusercontent.com/4898263/77974959-766d3a80-72ad-11ea-861c-4a040968f913.png)

I get back a 500 with the following traceback
```shell
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "/Users/emmanuelodeke/Desktop/django-apps/healthchecks-webapp/hc-venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/emmanuelodeke/Desktop/django-apps/healthchecks-webapp/hc-venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/emmanuelodeke/Desktop/django-apps/healthchecks-webapp/hc-venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/emmanuelodeke/Desktop/django-apps/healthchecks-webapp/hc-venv/lib/python3.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/Users/emmanuelodeke/Desktop/django-apps/healthchecks-webapp/hc-venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/emmanuelodeke/Desktop/django-apps/healthchecks-webapp/healthchecks/hc/accounts/views.py", line 156, in signup
    user = _make_user(email)
  File "/Users/emmanuelodeke/Desktop/django-apps/healthchecks-webapp/healthchecks/hc/accounts/views.py", line 67, in _make_user
    project.save()
  File "/Users/emmanuelodeke/Desktop/django-apps/healthchecks-webapp/hc-venv/lib/python3.7/site-packages/django/db/models/base.py", line 694, in save
    "unsaved related object '%s'." % field.name
ValueError: save() prohibited to prevent data loss due to unsaved related object 'owner'.
[31/Mar/2020 00:37:20] "POST /accounts/signup/ HTTP/1.1" 500 26544
```

where the inserted SQL was
```sql
SQL:  SELECT (1) AS a FROM auth_user WHERE auth_user.email = %s LIMIT 1
Args: ('emm.odeke@gmail.com',)
SQL:  INSERT INTO auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
Args: [2496276667594769591, '!zW8lVZcYxtLxtAGSOPlrVkhkkf0d1DNB3FnbLEOh', None, False, '5158970a-efaf-49e3-91f9-6428fa', '', '', 'emm.odeke@gmail.com', False, True, '2020-03-31T00:37:20.078044Z']
```

**Comment by odeke-em** [comment]
Interesting! Can we perhaps lazily generate the id field only when .save() is invoked, despite the monkey patching?

**Comment by timgraham** [comment]
This issue doesn't happen with Django 2.2.x. healthchecks automatically installs Django 3.0.x which we haven't done any testing with (behavior change bisected to https://github.com/django/django/commit/7254f1138d9c51fa558229c39c9559b369c4278a). I'd suggest that after Django 2.2.x support is completed, we create a separate branch for Django 3.0.x support. So django-spanner 2.2.x will work with Django 2.2.x, django-spanner 3.0.x with Django 3.0.x, etc.

**Comment by odeke-em** [comment]
Interesting, thank you for the note!

Perhaps let’s add this to the top of the README as a requirement.

**Comment by timgraham** [comment]
We can add a code check as well: https://github.com/googleapis/python-spanner-django/pull/416

**Comment by c24t** [comment]
> I'd suggest that after Django 2.2.x support is completed, we create a separate branch for Django 3.0.x support. So django-spanner 2.2.x will work with Django 2.2.x, django-spanner 3.0.x with Django 3.0.x, etc.

This seems like a pretty important decision!

**Comment by asthamohta** [comment]
Django 3.2.x is now supported so closing this issue
