### ISSUE TITLE
django-test-suite: force_insert_update.tests.ForceTests.test_force_update force save doesn't work

### ISSUE THREAD

**Issue by odeke-em** [googleapis/python-spanner-django#420]
Opening this issue with
```shell
======================================================================
ERROR: test_force_update (force_insert_update.tests.ForceTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/emmanuelodeke/Desktop/django-spanner/dmt/django/tests/force_insert_update/tests.py", line 33, in test_force_update
    c1.save(force_update=True)
  File "/Users/emmanuelodeke/Desktop/django-spanner/django_tests/django/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/emmanuelodeke/Desktop/django-spanner/django_tests/django/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/Users/emmanuelodeke/Desktop/django-spanner/django_tests/django/django/db/models/base.py", line 853, in _save_table
    raise DatabaseError("Forced update did not affect any rows.")
django.db.utils.DatabaseError: Forced update did not affect any rows.

----------------------------------------------------------------------
Ran 1 test in 6.900s
```

and from reading the code in the test, it seems to require an atomic Django transaction per
https://github.com/timgraham/django/blob/a091d2f5ca2dbc8c6cf0f3286f7d72489dde7b73/tests/force_insert_update/tests.py#L27-L34
![Screen Shot 2020-04-08 at 1 32 08 AM](https://user-images.githubusercontent.com/4898263/78762512-ca74c080-7938-11ea-9a60-0fec6f0ee830.png)

or perhaps a feature we don't support?
Anyways opening it so that we can add this to the tests' audit log.

**Comment by timgraham** [comment]
django-spanner's AutoField has a default value. I edited the test.
